version: '3'
services:
   client:
      build:
         context: .
         dockerfile: client.dev.Dockerfile
      ports:
         - 3000:3000
      volumes:
         - ./:/usr/src/app
         - /usr/src/app/node_modules
         - /usr/src/app/.next

   server:
      build:
         context: .
         dockerfile: server.dev.Dockerfile
      ports:
         - 3001:3001
      volumes:
         - ./:/usr/src/app
         - /usr/src/app/node_modules
